algorithm assign employees to shifts
yarinTag/YY-shifts pull request #37
Opened 2024-11-05 16:46 UTC by yarinTag

Need to pick a name for the strategy folder & more small changes

2024-11-06 09:20 UTC, yariv245 requested changes

2024-11-06 09:20 UTC, yariv245 commented on src/assignShifts.ts
> +        const shiftDuration =
wokr with LocalDate/LocalDateTime.until
Example from our code:
workCycle.start.until(workCycle.end).days();

2024-11-06 09:20 UTC, yariv245 commented on src/modules/shifts/shift.repository.ts
> +    return this.repository.find({ where: req, relations: ['availabilities'] });
use the value from request 
This from your shift.interface
findAllBy(req: GetRequest, relations?: string[]): Promise<Shift[]>;

2024-11-06 09:20 UTC, yariv245 commented on src/modules/shifts/shift.service.ts
> +    const shiftAssigner = new ShiftAssigner(strategy);
extract all this logs to another function

2024-11-06 09:20 UTC, yariv245 commented on src/noname/AssignmentStrategy.ts
> +        (time.end.atZone(ZoneId.UTC).toInstant().toEpochMilli() -
you have duplicate code remove the old one

2024-11-06 09:20 UTC, yariv245 commented on src/noname/interface.ts
> +export interface ShiftGroup {
?
/noname/

2024-11-06 09:20 UTC, yariv245 commented on src/noname/AssignmentStrategy.ts
> +export class DefaultUserAssignmentStrategy implements UserAssignmentStrategy {
where is the strategy?

2024-11-06 09:20 UTC, yariv245 commented on src/modules/shifts/shift.service.ts
> +    const strategy = new DefaultUserAssignmentStrategy(
I couldn't understand how the strategy works and why do you have 
const strategy = new DefaultUserAssignmentStrategy(
and
shiftAssigner = new ShiftAssigner(strategy);

2024-11-06 17:07 UTC, yarinTag commented on src/noname/AssignmentStrategy.ts
> +export class DefaultUserAssignmentStrategy implements UserAssignmentStrategy {
UserAssignmentStrategy: This is a blueprint for a strategy that assigns workers to shifts.

DefaultUserAssignmentStrategy: This is a specific implementation of the strategy that assigns workers randomly.

ShiftAssigner(acts as a chain of responsibility): This class coordinates the assignment process, choosing the appropriate strategy for different situations.

We can create different strategies for assigning workers, and the ShiftAssigner class decides which strategy to use.

The DefaultUserAssignmentStrategy is a basic strategy that assigns workers randomly, but you could create more complex strategies in the future.

2024-11-07 12:07 UTC, yarinTag commented on src/modules/shifts/shift.service.ts
> +    const strategy = new DefaultUserAssignmentStrategy(
I think it will be better to set a new table -> department-configuration/settings

2024-11-12 13:49 UTC, yariv245 approved these changes

2024-11-12 13:50 UTC, merged